# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  Default

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'


steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
    tags: |
      $(tag)
- task: Docker@2
  inputs:
    containerRegistry: 'ranidemos'
    repository: 'reddyrani/demos'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'