# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  default

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  # imageName: 'pipelines-javascript-docker'
  ImageName: 'reddyrani/devops:$(Build.BuildId)'


# - task: Docker@2
#   displayName: Build and Push an image
#   inputs:
#     containerRegistry: 'dockerhub-rani'
#     repository: 'reddyrani/devops'
#     command: 'buildAndPush'
#     Dockerfile: 'app/Dockerfile'
#     tags: '$(tag)'

- task: Docker@2
  inputs:
    containerRegistry: 'docker connection'
    repository: 'reddyrani/jsimages'
    command: 'buildAndPush'
    Dockerfile: 'app/Dockerfile'
    tags: '$(tag)'