# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  default

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'dockerhub-rani'
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-rani'
    repository: 'devops'
    command: 'buildAndPush'
    Dockerfile: 'app/Dockerfile'


